### PR TITLE
travis started failing recently. trying this as control

### PR DESCRIPTION
**Pull request by snd**
started failing here https://github.com/paritytech/parity-bridge/pull/152

trying this to rule out changes on the branch as cause

### CODE REVIEW

**Comment by snd** [comment]
sudo doesn't fix. seems like `parity` on travis doesn't have permissions to open sockets

**Comment by debris** [comment]
maybe let's open an issue upstream in travis repo?

**Comment by snd** [comment]
i'll try one last thing (not using snap) and then take this upstream

**Comment by snd** [comment]
downloading the parity binary directly (https://vanity-service.parity.io/parity-binaries?format=markdown&version=v1.9.5) seems to fix this. my guess is that the problem is due to some change in snap. will clean this up and throw out snap entirely

**Comment by snd** [comment]
ahaha. no. seems like this just suddenly started working again

**Pull request closed without merging**
