### PR TITLE
validator_set (in progress)

### PR DESCRIPTION
**Pull request by debris**

### CODE REVIEW

**Comment by rstormsf** [comment]
any progress @debris

**Comment by debris** [comment]
I didn't have time to get back to this yet, but @snd started looking into this problem recently

**Comment by snd** [comment]
@rstormsf there are a couple of edge cases to handle before we can continue implementation of the bridge with validator sets.

you can follow the progress at
https://github.com/paritytech/parity-bridge/pull/52

**Comment by bjornwgnr** [comment]
@rstormsf Do you guys want/need this for the oracles network mainnet launch?

**Pull request closed without merging**
